// The Datadog <-> AWS account integration.
//
// Streamed metrics arrive carrying only the dimensions CloudWatch puts on them. AWS *resource tags*
// -- which is where `stack`, `env`, and `block` live -- are collected separately, by Datadog calling
// the AWS tagging API through this role. Without it, metrics from the metric stream land untagged
// and cannot be attributed back to a Nullstone block.
//
// Off by default. The integration is account-scoped, so exactly one environment should own it per
// AWS account; enable it in each environment that has its own account.
locals {
  aws_integration_enabled = var.enable_aws_integration

  aws_integration_role_name = (
    var.aws_integration_role_name != "" ? var.aws_integration_role_name : "${local.resource_name}-integration"
  )
}

provider "datadog" {
  api_key = var.api_key
  app_key = var.app_key
  api_url = local.site_config.api_url
}

data "aws_caller_identity" "current" {}

// Created before the IAM role: Datadog generates the external ID, and the role's trust policy
// consumes it. This resource refers to the role only by name, so there is no cycle.
resource "datadog_integration_aws_account" "this" {
  count = local.aws_integration_enabled ? 1 : 0

  aws_account_id = data.aws_caller_identity.current.account_id
  aws_partition  = var.aws_partition

  auth_config {
    aws_auth_config_role {
      role_name = local.aws_integration_role_name
    }
  }

  // Scoped to this workspace's region by default. The metric stream is regional too, so widening
  // this only helps if you have resources Datadog should collect in other regions.
  aws_regions {
    include_only = length(var.aws_integration_regions) > 0 ? var.aws_integration_regions : [data.aws_region.current.region]
  }

  resources_config {
    // Resource collection is what pulls in resource metadata alongside the tags -- the whole point
    // of this integration for our purposes. It requires the AWS-managed SecurityAudit policy,
    // attached below; without it Datadog shows a warning on the AWS integration tile.
    extended_collection = var.aws_integration_resource_collection

    // Cloud Security Posture Management is a separate Datadog product. Left off; enable it
    // deliberately if you license it.
    cloud_security_posture_management_collection = false
  }

  metrics_config {
    enabled = true

    // The namespaces arriving through the metric stream are deliberately *not* excluded here.
    //
    // It is tempting to exclude them to avoid paying for both paths. Datadog's guidance is the
    // opposite: it detects the stream and stops polling those namespaces on its own, and polling is
    // also what collects the tags and metadata this integration exists for. Filtering them out risks
    // losing attribution to save nothing.
    //
    // See https://docs.datadoghq.com/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose/
    //
    // The provider requires exactly one of include_only/exclude_only, so this cannot be omitted.
    // The default mirrors Datadog's own: the three namespaces it excludes to keep GetMetricData
    // costs down.
    namespace_filters {
      exclude_only = var.aws_integration_excluded_namespaces
    }
  }

  // Logs reach Datadog through the Firehose delivery streams in this module, not through a Lambda
  // forwarder. Traces come from the app-level OTLP capabilities. Both are declared empty so Datadog
  // does not expect a forwarder that does not exist.
  logs_config {
    lambda_forwarder {}
  }

  traces_config {
    xray_services {}
  }
}

resource "aws_iam_role" "datadog_integration" {
  count = local.aws_integration_enabled ? 1 : 0

  name               = local.aws_integration_role_name
  tags               = local.tags
  assume_role_policy = data.aws_iam_policy_document.datadog_integration_assume[0].json
}

data "aws_iam_policy_document" "datadog_integration_assume" {
  count = local.aws_integration_enabled ? 1 : 0

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:${var.aws_partition}:iam::${var.datadog_aws_account_id}:root"]
    }

    // The external ID is generated by Datadog, not by us. Omitting this condition would leave the
    // role assumable by any Datadog customer who learned its ARN.
    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values   = [datadog_integration_aws_account.this[0].auth_config.aws_auth_config_role.external_id]
    }
  }
}

resource "aws_iam_role_policy" "datadog_integration" {
  count = local.aws_integration_enabled ? 1 : 0

  name   = "datadog-integration"
  role   = aws_iam_role.datadog_integration[0].id
  policy = data.aws_iam_policy_document.datadog_integration.json
}

// The bulk of the permission list comes from Datadog rather than from a copy kept here.
//
// Both data sources read the canonical set from Datadog's API, so the role tracks what Datadog
// actually needs as they add services. A hand-maintained list silently rots: the failure mode is a
// missing metric or an empty tag months later, with nothing pointing at the policy as the cause.
//
// The trade-off is that Datadog changing their list produces a diff here on the next plan. That is
// the intended behavior -- it surfaces the change instead of hiding it.
//
// A small baseline set is pinned below and unioned in, so the role never regresses below what
// Datadog's setup docs grant even if the API-published sets shift.
data "datadog_integration_aws_iam_permissions_standard" "this" {}

data "datadog_integration_aws_iam_permissions_resource_collection" "this" {}

locals {
  // The core permissions from Datadog's own AWS integration policy. These are the actions Datadog's
  // setup docs and CloudFormation template grant for account-level metric and metadata collection.
  //
  // They are listed explicitly rather than left to the data sources above because the API-published
  // sets do not always include all of them, and a missing one shows up as a whole service quietly
  // absent from Datadog rather than as an error. `distinct` below folds out the overlap, so
  // duplicates between this list and Datadog's are harmless.
  datadog_integration_baseline_permissions = [
    "account:GetAccountInformation",
    "apigateway:GET",
    "autoscaling:DescribeAutoScalingGroups",
    "autoscaling:DescribeScalingActivities",
    "budgets:ViewBudget",
    "dynamodb:ListTables",
    "ec2:DescribeInstances",
    "ec2:DescribeInstanceStatus",
    "ec2:DescribeSpotFleetRequests",
    "ec2:DescribeVolumes",
    "ecs:ListClusters",
    "elasticloadbalancing:DescribeLoadBalancers",
    "iam:ListAccountAliases",
    "ses:GetSendQuota",
    "ses:GetSendStatistics",
    "states:ListStateMachines",
    "trustedadvisor:ListRecommendations",
  ]

  datadog_integration_permissions = sort(distinct(concat(
    local.datadog_integration_baseline_permissions,
    data.datadog_integration_aws_iam_permissions_standard.this.iam_permissions,
    var.aws_integration_resource_collection ? data.datadog_integration_aws_iam_permissions_resource_collection.this.iam_permissions : [],
  )))
}

data "aws_iam_policy_document" "datadog_integration" {
  statement {
    sid       = "DatadogAWSIntegration"
    effect    = "Allow"
    actions   = local.datadog_integration_permissions
    resources = ["*"] // Datadog's own policy is account-wide; CloudWatch metrics cannot be scoped by resource anyway.
  }
}

// Resource collection requires this on top of the permissions above. Datadog's docs are explicit:
// "To use resource collection, you must attach AWS's managed SecurityAudit Policy to your Datadog
// IAM role." Enabling collection without it still works partially, but Datadog flags a warning on
// the AWS integration tile and metadata is incomplete.
resource "aws_iam_role_policy_attachment" "datadog_integration_security_audit" {
  count = local.aws_integration_enabled && var.aws_integration_resource_collection ? 1 : 0

  role       = aws_iam_role.datadog_integration[0].name
  policy_arn = "arn:${var.aws_partition}:iam::aws:policy/SecurityAudit"
}

resource "aws_iam_role_policy_attachment" "datadog_integration_additional" {
  for_each = local.aws_integration_enabled ? toset(var.aws_integration_additional_policy_arns) : toset([])

  role       = aws_iam_role.datadog_integration[0].name
  policy_arn = each.value
}
