// The Datadog <-> AWS account integration.
//
// Streamed metrics arrive carrying only the dimensions CloudWatch puts on them. AWS *resource tags*
// -- which is where `stack`, `env`, and `block` live -- are collected separately, by Datadog calling
// the AWS tagging API through this role. Without it, metrics from the metric stream land untagged
// and cannot be attributed back to a Nullstone block.
//
// Off by default. The integration is account-scoped, so exactly one environment should own it per
// AWS account; enable it in each environment that has its own account.
locals {
  aws_integration_enabled = var.enable_aws_integration

  aws_integration_role_name = (
    var.aws_integration_role_name != "" ? var.aws_integration_role_name : "${local.resource_name}-integration"
  )
}

provider "datadog" {
  api_key = var.api_key
  app_key = var.app_key
  api_url = local.site_config.api_url
}

data "aws_caller_identity" "current" {}

// Created before the IAM role: Datadog generates the external ID, and the role's trust policy
// consumes it. This resource refers to the role only by name, so there is no cycle.
resource "datadog_integration_aws_account" "this" {
  count = local.aws_integration_enabled ? 1 : 0

  aws_account_id = data.aws_caller_identity.current.account_id
  aws_partition  = var.aws_partition

  auth_config {
    aws_auth_config_role {
      role_name = local.aws_integration_role_name
    }
  }

  // Scoped to this workspace's region by default. The metric stream is regional too, so widening
  // this only helps if you have resources Datadog should collect in other regions.
  aws_regions {
    include_only = length(var.aws_integration_regions) > 0 ? var.aws_integration_regions : [data.aws_region.current.region]
  }

  resources_config {
    // Resource collection is what pulls in resource metadata alongside the tags -- the whole point
    // of this integration for our purposes. It requires the AWS-managed SecurityAudit policy,
    // attached below; without it Datadog shows a warning on the AWS integration tile.
    extended_collection = var.aws_integration_resource_collection

    // Cloud Security Posture Management is a separate Datadog product. Left off; enable it
    // deliberately if you license it.
    cloud_security_posture_management_collection = false
  }

  metrics_config {
    enabled = true

    // The namespaces arriving through the metric stream are deliberately *not* excluded here.
    //
    // It is tempting to exclude them to avoid paying for both paths. Datadog's guidance is the
    // opposite: it detects the stream and stops polling those namespaces on its own, and polling is
    // also what collects the tags and metadata this integration exists for. Filtering them out risks
    // losing attribution to save nothing.
    //
    // See https://docs.datadoghq.com/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose/
    //
    // The provider requires exactly one of include_only/exclude_only, so this cannot be omitted.
    // The default mirrors Datadog's own: the three namespaces it excludes to keep GetMetricData
    // costs down.
    namespace_filters {
      exclude_only = var.aws_integration_excluded_namespaces
    }
  }

  // Logs reach Datadog through the Firehose delivery streams in this module, not through a Lambda
  // forwarder. Traces come from the app-level OTLP capabilities. Both are declared empty so Datadog
  // does not expect a forwarder that does not exist.
  logs_config {
    lambda_forwarder {}
  }

  traces_config {
    xray_services {}
  }
}

resource "aws_iam_role" "datadog_integration" {
  count = local.aws_integration_enabled ? 1 : 0

  name               = local.aws_integration_role_name
  tags               = local.tags
  assume_role_policy = data.aws_iam_policy_document.datadog_integration_assume[0].json
}

data "aws_iam_policy_document" "datadog_integration_assume" {
  count = local.aws_integration_enabled ? 1 : 0

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:${var.aws_partition}:iam::${var.datadog_aws_account_id}:root"]
    }

    // The external ID is generated by Datadog, not by us. Omitting this condition would leave the
    // role assumable by any Datadog customer who learned its ARN.
    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values   = [datadog_integration_aws_account.this[0].auth_config.aws_auth_config_role.external_id]
    }
  }
}

// The bulk of the permission list comes from Datadog rather than from a copy kept here.
//
// Both data sources read the canonical set from Datadog's API, so the role tracks what Datadog
// actually needs as they add services. A hand-maintained list silently rots: the failure mode is a
// missing metric or an empty tag months later, with nothing pointing at the policy as the cause.
//
// The trade-off is that Datadog changing their list produces a diff here on the next plan. That is
// the intended behavior -- it surfaces the change instead of hiding it.
//
// A small baseline set is pinned below and unioned in, so the role never regresses below what
// Datadog's setup docs grant even if the API-published sets shift.
data "datadog_integration_aws_iam_permissions_standard" "this" {}

data "datadog_integration_aws_iam_permissions_resource_collection" "this" {}

locals {
  // The core permissions from Datadog's own AWS integration policy. These are the actions Datadog's
  // setup docs and CloudFormation template grant for account-level metric and metadata collection.
  //
  // They are listed explicitly rather than left to the data sources above because the API-published
  // sets do not always include all of them, and a missing one shows up as a whole service quietly
  // absent from Datadog rather than as an error. `distinct` below folds out the overlap, so
  // duplicates between this list and Datadog's are harmless.
  datadog_integration_baseline_permissions = [
    "account:GetAccountInformation",
    "apigateway:GET",
    "autoscaling:DescribeAutoScalingGroups",
    "autoscaling:DescribeScalingActivities",
    "budgets:ViewBudget",
    "dynamodb:ListTables",
    "ec2:DescribeInstances",
    "ec2:DescribeInstanceStatus",
    "ec2:DescribeSpotFleetRequests",
    "ec2:DescribeVolumes",
    "ecs:ListClusters",
    "elasticloadbalancing:DescribeLoadBalancers",
    "iam:ListAccountAliases",
    "ses:GetSendQuota",
    "ses:GetSendStatistics",
    "states:ListStateMachines",
    "trustedadvisor:ListRecommendations",
  ]

  datadog_integration_permissions = sort(distinct(concat(
    local.datadog_integration_baseline_permissions,
    data.datadog_integration_aws_iam_permissions_standard.this.iam_permissions,
    var.aws_integration_resource_collection ? data.datadog_integration_aws_iam_permissions_resource_collection.this.iam_permissions : [],
  )))
}

// Datadog's full permission set does not fit in an inline role policy, so these are customer-managed
// policies attached to the role instead.
//
// AWS caps the *aggregate* size of every inline policy on a role at 10,240 characters, and that
// quota cannot be raised. Splitting the actions across several inline policies therefore buys
// nothing -- they all draw on the same budget. Managed policies are budgeted individually at 6,144
// characters each, so the actions are chunked across as many as they need.
//
// IAM does not count whitespace toward either limit, so how the JSON is formatted is not a lever.
//
// See https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html
locals {
  // 6,144 is the hard cap. Budgeting under it leaves room for the statement envelope and for the one
  // action that straddles each boundary. The precondition below checks the real rendered documents
  // rather than trusting this figure.
  datadog_integration_policy_budget = 5500

  // Running total of the rendered cost of each action and every action before it. One action costs
  // its own length plus two quotes and a comma.
  //
  // Actions are packed into policies by this running total rather than by count. The list is sorted,
  // so same-service actions sit together and a by-count split can land a whole chunk on a long
  // prefix -- `elasticloadbalancing:` actions run ~50 characters against a ~33 character average,
  // which is enough to overrun the cap even though the average says it fits.
  datadog_integration_permission_offsets = [
    for i, action in local.datadog_integration_permissions :
    sum([for j in range(i + 1) : length(local.datadog_integration_permissions[j]) + 3])
  ]

  datadog_integration_permission_chars = sum([
    for action in local.datadog_integration_permissions : length(action) + 3
  ])

  datadog_integration_policy_count = floor(
    local.datadog_integration_permission_chars / local.datadog_integration_policy_budget
  ) + 1

  datadog_integration_permission_chunks = [
    for bucket in range(local.datadog_integration_policy_count) : [
      for i, action in local.datadog_integration_permissions : action
      if floor(local.datadog_integration_permission_offsets[i] / local.datadog_integration_policy_budget) == bucket
    ]
  ]

  // Every managed policy on the role counts against the same quota: the chunks here, SecurityAudit
  // when resource collection is on, and anything the caller adds.
  datadog_integration_attached_policy_count = (
    length(local.datadog_integration_permission_chunks)
    + (var.aws_integration_resource_collection ? 1 : 0)
    + length(var.aws_integration_additional_policy_arns)
  )
}

data "aws_iam_policy_document" "datadog_integration" {
  count = length(local.datadog_integration_permission_chunks)

  statement {
    sid       = "DatadogAWSIntegration${count.index}"
    effect    = "Allow"
    actions   = local.datadog_integration_permission_chunks[count.index]
    resources = ["*"] // Datadog's own policy is account-wide; CloudWatch metrics cannot be scoped by resource anyway.
  }
}

resource "aws_iam_policy" "datadog_integration" {
  count = local.aws_integration_enabled ? length(local.datadog_integration_permission_chunks) : 0

  name   = "${local.aws_integration_role_name}-${count.index}"
  tags   = local.tags
  policy = data.aws_iam_policy_document.datadog_integration[count.index].json

  lifecycle {
    // Measures the document AWS will actually measure -- rendered, with whitespace stripped, since
    // IAM ignores it. Catches an undersized budget at plan time instead of as a LimitExceeded on
    // apply, which is how this was found the first time.
    precondition {
      condition = length(replace(
        data.aws_iam_policy_document.datadog_integration[count.index].json, "/\\s/", ""
      )) <= 6144

      error_message = "Datadog integration policy ${count.index} exceeds the 6,144 character managed policy limit. Lower datadog_integration_policy_budget in aws-integration.tf so the permissions split across more policies."
    }
  }
}

resource "aws_iam_role_policy_attachment" "datadog_integration" {
  count = local.aws_integration_enabled ? length(local.datadog_integration_permission_chunks) : 0

  role       = aws_iam_role.datadog_integration[0].name
  policy_arn = aws_iam_policy.datadog_integration[count.index].arn
}

// A warning rather than an error: the quota defaults to 10 but is self-service raisable to 25, so
// failing the plan would be wrong for an account that has already raised it. Naming the cause here
// beats reading an opaque LimitExceeded on the attachment.
check "datadog_integration_policy_quota" {
  assert {
    condition = !local.aws_integration_enabled || local.datadog_integration_attached_policy_count <= 10

    error_message = "The Datadog integration role needs ${local.datadog_integration_attached_policy_count} managed policies, above the default quota of 10 per role. Request an increase (self-service, up to 25) or set aws_integration_resource_collection = false."
  }
}

// Resource collection requires this on top of the permissions above. Datadog's docs are explicit:
// "To use resource collection, you must attach AWS's managed SecurityAudit Policy to your Datadog
// IAM role." Enabling collection without it still works partially, but Datadog flags a warning on
// the AWS integration tile and metadata is incomplete.
resource "aws_iam_role_policy_attachment" "datadog_integration_security_audit" {
  count = local.aws_integration_enabled && var.aws_integration_resource_collection ? 1 : 0

  role       = aws_iam_role.datadog_integration[0].name
  policy_arn = "arn:${var.aws_partition}:iam::aws:policy/SecurityAudit"
}

resource "aws_iam_role_policy_attachment" "datadog_integration_additional" {
  for_each = local.aws_integration_enabled ? toset(var.aws_integration_additional_policy_arns) : toset([])

  role       = aws_iam_role.datadog_integration[0].name
  policy_arn = each.value
}
